### ISSUE TITLE
Link to Elisp Programming and Customization

### ISSUE THREAD

**Issue by yuravg** [p3r7/awesome-elisp#18]
Hi, I think this link will be helpful for your project

[caiorss/Emacs-Elisp-Programming](https://github.com/caiorss/Emacs-Elisp-Programming/blob/master/Elisp_Programming.org)

**Comment by p3r7** [comment]
Hi

Yes, this resource is really good but in fact already listed: https://github.com/p3r7/awesome-elisp#emacs-in-a-box---elisp-programming

**Comment by yuravg** [comment]
Sorry, I didn't see it.

**Comment by p3r7** [comment]
Don't worry and thanks for contributing anyway :smiley:
