### ISSUE TITLE
Bad link in subsection "edebug"

### ISSUE THREAD

**Issue by purlupar** [p3r7/awesome-elisp#20]
In "Interactive Development & Debugging" -> "edebug", the second link ("Endless parentheses ...") is going to the same destination as the first link. Should go to https://endlessparentheses.com/debugging-elisp-part-2-advanced-topics.html, I think. (BTW: Great list, thanks!)

**Comment by p3r7** [comment]
Oopsie, well spotted.

Just fixed the link.

Thanks for reporting & tanks for the compliment ;)
