### ISSUE TITLE
This link is broken

### ISSUE THREAD

**Issue by OrionRandD** [p3r7/awesome-elisp#23]
(Almost) All You Need to Know About Variables
[read online](https://with-emacs.com/posts/tutorials/almost-all-you-need-to-know-about-variables/)

A must read!

**Comment by jamiebill** [comment]
https://web.archive.org/web/20210119140336/https://with-emacs.com/posts/tutorials/almost-all-you-need-to-know-about-variables/

I was going to post about the same issue, so I'll add this here instead -- the above is a working link to the same post from the Wayback Machine, in case that helps. Cheers

**Comment by danielnemenyi** [comment]
The author wrote a very similar piece for opensource.com which I'd suggest changing the URL to instead, as the page archived by the waybackmachine doesn't offer any improvements over it.

As above (you can see my github workflow is a bit rusty!) suggest updating the url to: https://opensource.com/article/20/3/variables-emacs

**Comment by p3r7** [comment]
thanks to the 3 of you.

fixed w/ https://github.com/p3r7/awesome-elisp/commit/8caa547918959829925c814f1f68ce71b16fd164
