### ISSUE TITLE
Update this link

### ISSUE THREAD

**Issue by OrionRandD** [p3r7/awesome-elisp#24]
ergoemacs - Practical Emacs Lisp
[read online](http://ergoemacs.org/emacs/elisp.html)

to:

http://xahlee.info/emacs/emacs/elisp.html

**Comment by p3r7** [comment]
thanks!

fixed w/ https://github.com/p3r7/awesome-elisp/commit/f91d8ffa570cb1073f6bbca8431bcf32430b6b05
