### ISSUE TITLE
Elisp Repo Kit

### ISSUE THREAD

**Issue by psionic-k** [p3r7/awesome-elisp#27]
https://github.com/positron-solutions/elisp-repo-kit

For setting up a ready-made github repo that has all the bells and whistles and string renaming done.

Also going in the direction of EDE but mostly focused on streamlining distribution and some development.

**Comment by p3r7** [comment]
hey.

that's a nice one. could you propose a PR w/ a new entry under the [building](https://github.com/p3r7/awesome-elisp#building) section?

cheers
