### ISSUE TITLE
Mention Eask?

### ISSUE THREAD

**Issue by jcs090218** [p3r7/awesome-elisp#29]
Hi, @p3r7!

The topic says it all. :) Could you mention [eask](https://github.com/emacs-eask/cli) in the **Building** section? Maybe somewhere close to [cask](https://github.com/cask/cask)? 🤔

Thank you!

**Comment by p3r7** [comment]
sure!

would you make a PR w/ a small description (one sentence or two) about how it compares/differ from the rest?

**Comment by jcs090218** [comment]
@p3r7 I've opened the PR in #30. :)

**Comment by jcs090218** [comment]
@p3r7 Friendly ping. :)

**Comment by p3r7** [comment]
hey!

sorry this flew under the radar. just merged.
