### ISSUE TITLE
Remove unfriendly harassment statement

### ISSUE THREAD

**Issue by gnusupport** [p3r7/awesome-elisp#31]
Github is not place for harassment and defamation:

![2024-11-08_10-29](https://github.com/user-attachments/assets/e9337ae9-7f52-4a67-a7e0-a2fc50b983ad)

based on that I am kindly asking you to remove the defamatory statement on Xah Lee where it says:
```
"he is [notorious for trolling](http://xahlee.info/emacs/emacs/_p/KickbanXahLeeFromEmacsChannel.htm)"
```

I suggest following description of Xah Lee:

Xah Lee is a prolific and dedicated contributor to the Emacs and Emacs Lisp community. Known for his extensive tutorials, articles, and innovative packages, he has helped countless users better understand Emacs, particularly through practical examples and detailed guides. His resources cover a broad spectrum of topics, from text editing and keybinding optimizations to in-depth explanations of Emacs Lisp, making advanced concepts more accessible.

One of his notable contributions, xah-fly-keys, is a powerful modal editing system that blends elements of both Emacs and Vim, aimed at improving typing ergonomics. This package, along with many others he's created, reflects his commitment to enhancing Emacs’ usability and versatility, especially for users interested in efficient workflows.

Through his contributions, Xah Lee has become a valuable resource in the Emacs ecosystem, known for pushing boundaries and encouraging users to explore Emacs’ full potential. His efforts have empowered both newcomers and seasoned users to make the most out of this powerful text editor.

**Comment by p3r7** [comment]
thanks for reporting.

i do agree we need to edit this description. this was originally taken from my personal notes and shoud not have ended up here. at a time when Xah was voluntarily referring himself as such (in old xah talk shows notably) but obviously this was in no way giving the permission for others to do the same.

furthermore his persona seem to have evolved quite a bit other time and this section only refered to a short lived period when he was known to act as such.

thanks for the recommanded description. it is somewhat a tad more verbose than the one given to others. i'll make it more concise but use it as a basis.

**Comment by p3r7** [comment]
done.

i'm closing the issue, but don't hesitate to comment if you have any additional suggestion.

**Comment by gnusupport** [comment]
Xah do a lot of training for people over YouTube. See here: https://www.youtube.com/@XahLee/search?query=emacs that is rich resource for many people and view count is over 600 or over 1000 per video. He has community on YouTube.
