### ISSUE TITLE
Move project to an organisation

### ISSUE THREAD

**Issue by p3r7** [p3r7/awesome-elisp#6]
I don't feel that being having a single person be the "owner" of the project would help it develop.

I would rather have it transferred to an organization.

Possible solutions:
 - contact and join [emacs-tw](https://github.com/emacs-tw) who already own [awesome-emacs](https://github.com/emacs-tw/awesome-emacs)
 - create one. Just name it `awesome-elisp`?

**Comment by jcs090218** [comment]
Hi, @p3r7!

I’m from `emacs-tw` and wanted to check if you’re still interested in transferring this repo to the `emacs-tw` organization. Could you share your current plans for this repo/issue? :)

**Comment by p3r7** [comment]
hey!

> still interested in transferring this repo to the `emacs-tw` organization.

definitely!

> Could you share your current plans for this repo/issue? :)

my initial idea was to keep it up to date w/ general elisp libs / tooling (there is a section that tries to define the [`scope`](https://github.com/p3r7/awesome-elisp?tab=readme-ov-file#scope) of this document).

i try to keep up w/ major libs & tools being release (following the Sacha Chua blog) but i do this in a best effort way and am most likely missing quite a few things. i do get recommendations through PRs and issues but having this repo under a well maintained emacs-centric github org is certainly way more sane.

or course the document could be restructured to remove any overlap w/ `awesome-emacs` and make it echo better.

i do like how `awesome-elisp` has a tad more verbose format than most `awesome-*` projects, though. but that might just be a me thing.

**Comment by jcs090218** [comment]
Got it! Thanks for the explanation! I have no issues with how `awesome-emacs` is structured, but I do like the structure of `awesome-elisp`! :)

> definitely!

Could you transfer the repo to me? I’ll then transfer it to the organization and add you as a collaborator. What do you think? :)

**Comment by p3r7** [comment]
that seems to be the way to do it for external orgs.

this works for me.

---

EDIT: i've just done it. you should get a notification w/ a "transfer request" you have to approve iirc.

**Comment by jcs090218** [comment]
Awesome! I just moved it to the `emacs-tw` organization. 😊

It looks like you're already a collaborator (I didn't realize that), so I don't think there's any need to send a collaborator invitation. 🙂

**Comment by p3r7** [comment]
yay! awesome.
